-- =============================================================================
-- migrate-add-contador-role.sql
--
-- Agrega el rol "contador" al enum app_role_enum, para usuarios que solo
-- necesitan ver la pestaña "Para el Contador" (declaración mensual de IVA
-- e ISR) sin acceso al resto de la app.
--
-- INSTRUCCIONES:
-- 1. Abrir Supabase Dashboard → SQL Editor.
-- 2. Pegar y ejecutar SOLO la línea del ALTER TYPE (la única abajo).
-- 3. Para VERIFICAR, abrir UNA NUEVA query (otra ejecución) y correr:
--      SELECT unnest(enum_range(NULL::app_role_enum));
--    Postgres exige que ALTER TYPE ENUM se "committee" antes de poder usar
--    el nuevo valor — si lo metes en la misma transacción/run, falla con
--    "unsafe use of new value" y REVIERTE TODO (incluyendo el ALTER).
-- 4. Entrar a /usuarios en la app e invitar al contador con rol "Contador".
--
-- SAFE: ADD VALUE con IF NOT EXISTS es idempotente. Corre dos veces sin
-- error. No toca filas existentes.
-- =============================================================================

ALTER TYPE app_role_enum ADD VALUE IF NOT EXISTS 'contador';
